spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dtoPractice_db
    password: Eziomanish@1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: 'true'

welcome:
  message: welcome to data transfer object (dto ) practice

